import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { loadConfig } from "./config.js";
import { createPorts, createWatchReaders } from "./brokers/index.js";
import { createEngine } from "./engine.js";
import { createMcpServer } from "./mcp.js";
import { createNotifier } from "./notify.js";
import { createRelayServer } from "./server.js";
import { createStorage } from "./storage/index.js";
import { VERSION } from "./version.js";

const HELP = `trade-relay v${VERSION} — open-source execution relay for trading alerts

Usage:
  trade-relay init                Create trade-relay.config.json and .env here
  trade-relay start               Run the relay (webhook + dashboard + API)
  trade-relay mcp                 Run the MCP server on stdio (for AI agents)
  trade-relay simulate            Fire a test alert at the running relay
  trade-relay --version

Options:
  --config <path>                 Config file (default ./trade-relay.config.json,
                                  or $TRADE_RELAY_CONFIG)

Docs: https://github.com/LuxAlgo/trade-relay
`;

const arg = (name: string): string | undefined => {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
};

const configPath = (): string => arg("--config") ?? process.env["TRADE_RELAY_CONFIG"] ?? "./trade-relay.config.json";

const loadDotEnv = (): void => {
  try {
    process.loadEnvFile(".env");
  } catch {
    // No .env file is fine — the environment may already carry the vars.
  }
};

const INIT_CONFIG = {
  // agentTokenScope defaults to "read": the agent token can inspect
  // everything and hit the kill switch, never trade, until you widen it.
  server: { port: 8484, dashboardToken: "${DASHBOARD_TOKEN}", agentToken: "${AGENT_TOKEN}" },
  storage: { driver: "sqlite", path: "./trade-relay.db" },
  accounts: [
    { id: "sim", broker: "simulator", startingEquity: 100_000 },
    // To trade an Alpaca PAPER account instead, add:
    // { "id": "paper", "broker": "alpaca", "credentials": { "apiKey": "${ALPACA_KEY}", "apiSecret": "${ALPACA_SECRET}" } }
  ],
  endpoints: [
    {
      id: "tradingview",
      token: "${WEBHOOK_TOKEN}",
      parser: "auto",
      account: "sim",
      defaults: { sizing: { mode: "quantity", value: 1 }, orderType: "market" },
      risk: {
        symbolAllowlist: ["AAPL", "SPY", "BTCUSD"],
        maxPositionSize: { quantity: 100 },
        maxDailyLoss: 1000,
        maxOrdersPerDay: 50,
        dedupeWindowSec: 10,
      },
    },
  ],
  notifications: [],
  mcp: { allowTrading: false },
};

const init = (): void => {
  const path = "./trade-relay.config.json";
  if (existsSync(path)) {
    console.error(`${path} already exists — not overwriting.`);
    process.exit(1);
  }
  // JSON has no comments; strip the hint line above before writing.
  writeFileSync(path, JSON.stringify(INIT_CONFIG, null, 2) + "\n");
  if (!existsSync("./.env")) {
    const webhookToken = randomBytes(24).toString("hex");
    const dashboardToken = randomBytes(24).toString("hex");
    const agentToken = randomBytes(24).toString("hex");
    writeFileSync(
      "./.env",
      [
        "# Generated by trade-relay init — keep this file out of git.",
        `WEBHOOK_TOKEN=${webhookToken}`,
        `DASHBOARD_TOKEN=${dashboardToken}`,
        "# Read-only key for agents/integrations — safe to hand out, rotate to revoke.",
        `AGENT_TOKEN=${agentToken}`,
        "# For an Alpaca PAPER account (key id starts with PK):",
        "# ALPACA_KEY=",
        "# ALPACA_SECRET=",
        "",
      ].join("\n"),
    );
  }
  console.log("Created trade-relay.config.json and .env (with generated tokens).");
  console.log("");
  console.log("Next:");
  console.log("  1. trade-relay start");
  console.log("  2. open the dashboard at http://localhost:8484 (token is DASHBOARD_TOKEN in .env)");
  console.log("  3. point your alert at POST /webhook/<WEBHOOK_TOKEN>");
  console.log("  4. or fire a test: trade-relay simulate");
};

const assemble = () => {
  const config = loadConfig(configPath());
  const storage = createStorage(config.storage);
  const ports = createPorts(config);
  const watchReaders = createWatchReaders(config);
  const notifier = createNotifier(config.notifications);
  const engine = createEngine({ config, storage, ports, notifier });
  return { config, storage, ports, watchReaders, notifier, engine };
};

const start = (): void => {
  loadDotEnv();
  const { config, storage, watchReaders, engine } = assemble();
  const server = createRelayServer({ config, engine, storage, watchReaders, version: VERSION });
  server.listen(config.server.port, config.server.host, () => {
    const local = `http://localhost:${config.server.port}`;
    console.log(`trade-relay v${VERSION}`);
    console.log(`  dashboard  ${local}`);
    for (const endpoint of config.endpoints) {
      console.log(`  webhook    POST ${local}/webhook/${endpoint.token}  (endpoint "${endpoint.id}" → account "${endpoint.account}")`);
    }
    for (const account of engine.status().accounts) {
      console.log(`  account    ${account.id} — ${account.broker} (${account.environment})`);
      if (account.environment === "live") {
        console.log(`  ⚠ LIVE     "${account.id}" places REAL orders with REAL money. The rails are on; check them anyway.`);
      }
    }
    if (!config.server.dashboardToken) {
      console.log("  note       no dashboardToken configured: the API answers loopback requests only");
    }
    if (config.server.agentToken) {
      console.log(`  agent      agent token active, scope "${config.server.agentTokenScope}" (read-only unless set to "trade")`);
    }
    console.log("  safety     rails ON; kill switch and flatten live in the dashboard");
  });
  const shutdown = (): void => {
    console.log("\nshutting down…");
    server.close(() => {
      storage.close();
      process.exit(0);
    });
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
};

const mcp = async (): Promise<void> => {
  loadDotEnv();
  const { config, storage, watchReaders, engine } = assemble();
  const server = createMcpServer({ config, engine, storage, watchReaders });
  // stdout is the MCP protocol channel — everything human goes to stderr.
  console.error(`trade-relay MCP v${VERSION} (trading ${config.mcp.allowTrading ? "ENABLED" : "disabled"})`);
  await server.connect(new StdioServerTransport());
};

const simulate = async (): Promise<void> => {
  loadDotEnv();
  const config = loadConfig(configPath());
  const endpoint = config.endpoints[0]!;
  const symbol = endpoint.risk.symbolAllowlist?.[0] ?? "AAPL";
  const payload = { action: "buy", symbol, quantity: 1, price: 100, signalId: `sim-${Date.now()}` };
  const url = `http://localhost:${config.server.port}/webhook/${endpoint.token}`;
  console.log(`POST ${url}`);
  console.log(JSON.stringify(payload, null, 2));
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  console.log(`→ ${response.status}`);
  console.log(JSON.stringify(await response.json(), null, 2));
};

const command = process.argv[2];
if (command === "init") init();
else if (command === "start") start();
else if (command === "mcp") void mcp();
else if (command === "simulate") void simulate().catch((error: unknown) => {
  console.error(`simulate failed: ${(error as Error).message} — is the relay running? (trade-relay start)`);
  process.exit(1);
});
else if (command === "--version" || command === "-v" || command === "version") console.log(VERSION);
else {
  console.log(HELP);
  if (command && command !== "help" && command !== "--help") process.exit(1);
}
